const CLIENT_ROUTES = {
  home: "/",
  about: "/about",
  profile: "/profile",
  rewards: "/rewards",
  finance: "/finance",
  account: "/account",
  cards: "/cards",
  editAccount: "/editAccount",
  auth: "/auth",
  authWelcome: "/auth/welcome",
  authSignin: "/auth/signin",
  authSignup: "/auth/signup",
  authVerifyEmail: "/auth/verify-email",
  authResendEmail: "/auth/resend-email",
  authForgetPasscode: "/auth/forget-passcode",
  authResetPasscode: "/auth/reset-passcode",
  liveChat: "/livechat",
  allTransactions: "/transactions",
  addMoney: "/add-money",
  sendMoneyInHouse: "/send-money/In-house",
  sendMoneyBank: "/send-money/bank",
  sendMoneyMobile: "/send-money/mobile",
  _404: "/404",
};

export { CLIENT_ROUTES };
